### ISSUE TITLE
Has ValueError "Must pass 2-d input" while Long Short Term Memory Classifier(Binary Classification)

### ISSUE THREAD

**Issue by klcheung99** [abhinav-bhardwaj/Network-Intrusion-Detection-Using-Machine-Learning#3]
When I ran  Long Short Term Memory Classifier(Binary Classification), it showed Value Error. How can I solve this problem? Thanks Thanks so much! 
--> 324         raise ValueError(f"Must pass 2-d input. shape={values.shape}")

![image](https://user-images.githubusercontent.com/76594282/130828855-12b5b92b-d412-4444-9d78-831dee606a33.png)

**Comment by abhinav-bhardwaj** [comment]
Include the below code 
```X_test = X_test.to_numpy()```
before executing this 
```x_test = np.reshape(X_test, (X_test.shape[0],X_test.shape[1],1))```

This will fix the problem.

Closing the issue. Reopen if this issue arises again.

**Comment by klcheung99** [comment]
Abhinav, thank you so much! 
Do you have LSTM Classifier (Multi-class Classification). 
Moreover, I would want to use SHAP (SHapley Additive exPlanations), to explain the hidden layer and your model (KNN and LSTM), to see what features are the top important features while determining the result of model. however, there has some bugs.. I am so sorry to disturb you. but I spend a week to debug still got nothing. It will be great thankful if you have time to take a look! Thank you so much! Wish you have a nice weekend.

KNN SHAP explainer
`!pip install shap
import shap

knn_explainer = shap.KernelExplainer(knn.predict,X_test)
knn_shap_values = knn_explainer.shap_values(X_test)
shap.summary_plot(knn_shap_values, X_test)
shap.dependence_plot("intrusion", knn_shap_values, X_test)

shap.force_plot(knn_explainer.expected_value,knn_shap_values[10,:], X_test.iloc[10,:])
shap.force_plot(knn_explainer.expected_value, knn_shap_values, X_test)`

LSTM SHAP explainer
`import shap

explainer = shap.DeepExplainer(lstm, x_train)
shap_values = explainer.shap_values(x_test)
shap.initjs()`

**Comment by abhinav-bhardwaj** [comment]
@klcheung99 Thank you for mentioning this. At the moment I don't have LSTM for Multi-class but I will make sure to include that soon. Also, I will look into the SHAP issue.
